const Products = [
  {
    _id: "1",
    name: "airpods oneaplus",
    image: "./images/airpods oneaplus.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "2000",
    countInStock: "23",
    rating: "2.5",
    numReviews: "45",
  },
  {
    _id: "2",
    name: "airpods samsung",
    image: "./images/airpods samsung.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "3800",
    countInStock: "43",
    rating: "3.6",
    numReviews: "49",
  },
  {
    _id: "3",
    name: "canon ",
    image: "./images/canon .jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "150000",
    countInStock: "7",
    rating: "4",
    numReviews: "23",
  },
  {
    _id: "4",
    name: "huawai",
    image: "./images/huawai.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "45000",
    countInStock: "11",
    rating: "4.5",
    numReviews: "65",
  },
  {
    _id: "5",
    name: "i phone 11",
    image: "./images/i phone 11.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "55000",
    countInStock: "0",
    rating: "3",
    numReviews: "765",
  },
  {
    _id: "6",
    name: "iPhone 7",
    image: "./images/iPhone 7.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "65000",
    countInStock: "21",
    rating: "5",
    numReviews: "87",
  },
  {
    _id: "7",
    name: "mac-pro",
    image: "./images/mac-pro.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "80000",
    countInStock: "5",
    rating: "4",
    numReviews: "28",
  },
  {
    _id: "8",
    name: "novel",
    image: "./images/novel.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "5000",
    countInStock: "6",
    rating: "5",
    numReviews: "632",
  },
  {
    _id: "9",
    name: "patak philip",
    image: "./images/patak philip.jpg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Mechanical",
    price: "400000",
    countInStock: "8",
    rating: "4.5",
    numReviews: "46",
  },
  {
    _id: "10",
    name: "patek_philippe straps",
    image: "./images/patek_philippe straps.jpg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Mechanical",
    price: "500000",
    countInStock: "4",
    rating: "3",
    numReviews: "90",
  },
  {
    _id: "11",
    name: "powerbank Mi",
    image: "./images/powerbank Mi.jpeg",
    description:
      "Awesom product -fully functional handy best selling product easy to replace no falgsgip product best rated",
    brand: "",
    catagory: "Electronics",
    price: "3000",
    countInStock: "98",
    rating: "2",
    numReviews: "23",
  },
];
export default Products;
